name: "ODE Web Interface"
version: "1.0.3"
slug: "ode-web-interface"
description: "Web interface for Open Dynamic Export with Ingress support"
url: "https://github.com/longzheng/open-dynamic-export"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
ingress: true
ingress_port: 8099
panel_icon: mdi:solar-power
panel_title: "Solar Export"
ports:
  8099/tcp: null
options:
  ode_host: "homeassistant.local"
  ode_port: 3000
schema:
  ode_host: str
  ode_port: port
